[package]
name = "c-api"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "mp4"
crate-type = ["staticlib"]

[dependencies]
shiguredo_mp4 = { path = "../../", default-features = false }

[build-dependencies]
cbindgen = { version = "0.29.2", default-features = false }

