[package]
name = "c-api"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
shiguredo_mp4 = { path = "../../" }

[build-dependencies]
cbindgen = { version = "0.29.2", default-features = false }

